console.log("-Pasos para aprender a programar")
console.log("")
console.log("-Informarte")
console.log("")
console.log("investigar")
console.log("")
console.log("ver video en YouTobe(para ver si te gusta)")
console.log("")
console.log("empezar un curso")
console.log("prestar atencion a la clase")
console.log("")
console.log("ir probando los codigos")
console.log("")
console.log("practicar")
console.log("")
console.log("")