console.log("-preparacion de torta")
console.log("-ir al supermercado")
console.log("-comprarlos ingredientes")
console.log("-buscar las cosas necesarias para concinar")
console.log("-tomar las medidas")
console.log("-mezclar los ingredientes secos")
console.log("-incorporar ingredientes humedos hasta lograr mezcla homogenea ")
console.log("-precalentar el horno")
console.log("-sacarlo cuando este listo")
console.log("-esperar que se enfrie")