
console.log("-avanzar")
console.log("-quitas")
console.log("-avanzar")
console.log("-quitas")
console.log("-avanzar")
console.log("-quitas")
console.log("avanzar")
console.log("-quitas")
console.log("-girar a la izquierda")
console.log("-avanzar")
console.log("-quitas")
console.log("-avanzar")
console.log("-quitas")
console.log("-avanzar")
console.log("-quitas")
console.log("-avanzarr")
console.log("-quitas")
